"""create citas table

Revision ID: 3388b565e934
Revises: 3ed01c13453f
Create Date: 2026-03-16 18:59:40.175294

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3388b565e934'
down_revision: Union[str, None] = '3ed01c13453f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('psicologo_id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('confirmada', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['psicologo_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    # ### end Alembic commands ###
